name: Package analyzer (main)
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  branch_protection_rule:
    types: [created, completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run analyzer
        uses: ./.github/action_files/main

