name: Package analyzer
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  branch_protection_rule:
    types: [created, completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: analyze-stable
        uses: flutterings/dart-package-analyzer@v1
        with:
          flutter_version: '3.16.4'
          flutter_channel: 'stable'
